name: hani_evan
favicon: null
layout_spectrum: 0.6037529257591814
typography_spectrum: 0.5947851503733546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.911362202372402
  lightness: 0.014974129851907492
  saturation: 0.1395046089310199
  rhythmicContrast: 0.11429263628087938
purpose: []
